export const landingContent = {
  brand: 'ProGenEDA',
  nav: [
    { label: 'Product', href: '#product' },
    { label: 'Pipeline', href: '#pipeline' },
    { label: 'Market', href: '#market' },
    { label: 'Proof', href: '#proof' },
    { label: 'Roadmap', href: '#roadmap' },
  ],
  hero: {
    eyebrow: 'A compiler layer for circuit design',
    title: ['Circuit intent in.', 'Native EDA files out.'],
    body:
      'Describe a circuit, provide structured JSON, or define components and connections. ProGenEDA compiles the intent into project files that open in the engineering tools you already use.',
    primaryCta: { label: 'Request early access', href: 'mailto:request@progeneda.app?subject=ProGenEDA%20Early%20Access' },
    secondaryCta: { label: 'Open the demo', href: '/login' },
    note: 'Early technical alpha. Supported components and circuit sizes are currently limited.',
  },
  proofPoints: [
    { value: '4', label: 'native EDA ecosystems', detail: 'KiCad, EasyEDA Pro, LTspice, Proteus' },
    { value: '103', label: 'KiCad registry words', detail: 'July 2026 release manifest' },
    { value: '600/600', label: 'KiCad corpus pass', detail: 'Combination-mode final validation' },
    { value: '0', label: 'model calls for edits', detail: 'Deterministic value recompilation' },
  ],
  acts: [
    { number: '01', label: 'The work' },
    { number: '02', label: 'The structure' },
    { number: '03', label: 'The compiler' },
    { number: '04', label: 'The outputs' },
    { number: '05', label: 'The proof' },
  ],
  files: [
    { tool: 'KiCad', extension: '.kicad_sch', name: 'filter.kicad_sch', accent: 'blue' },
    { tool: 'LTspice', extension: '.asc', name: 'filter.asc', accent: 'red' },
    { tool: 'Proteus', extension: '.pdsprj', name: 'filter.pdsprj', accent: 'gold' },
  ],
  architecture: [
    { index: '01', title: 'Interpret', label: 'AI boundary', body: 'Turn incomplete human intent into explicit components, values, pins, nets, and constraints.' },
    { index: '02', title: 'Normalize', label: 'CircuitIR / JSON', body: 'Keep the logical circuit independent of any one EDA vendor or file format.' },
    { index: '03', title: 'Validate', label: 'Deterministic checks', body: 'Reject unsupported parts, invalid pins, merged nets, geometry violations, and incomplete contracts.' },
    { index: '04', title: 'Compile', label: 'Tool-specific exporter', body: 'Write exact KiCad, EasyEDA Pro, LTspice, or Proteus project structures with code, not model prose.' },
  ],
  pipeline: [
    {
      index: '01',
      phase: 'Intent',
      owner: 'AI boundary',
      body: 'Accept natural language, logic, component lists, or direct JSON. Use a model only when human intent must be interpreted.',
      stages: ['Prompt normalization', 'Completeness checks', 'Intent parsing when needed', 'Canonical main JSON'],
    },
    {
      index: '02',
      phase: 'Contract',
      owner: 'Shared deterministic core',
      body: 'Normalize the request into explicit components, references, values, pins, nets, constraints, and target metadata.',
      stages: ['Schema validation', 'Input fixer', 'Supported-word registry', 'Pin and net normalization'],
    },
    {
      index: '03',
      phase: 'Construct',
      owner: 'Native schematic pipeline',
      body: 'Build and score placement variants, improve coordinates, choose wire/terminal policy, and emit native schematic structures.',
      stages: ['Component placement', 'Placement validation', 'Arrangement decision', 'Beautifier', 'Wire / terminal planner', 'Native wire writer'],
    },
    {
      index: '04',
      phase: 'Prove',
      owner: 'Hosted validators',
      body: 'Parse the generated artifact back into a graph and compare it against the intended circuit before release.',
      stages: ['Value validation', 'Native file parsing', 'Expected-net comparison', 'Pin conflict checks', 'Geometry checks', 'Final validation report'],
    },
    {
      index: '05',
      phase: 'Physical*',
      owner: 'KiCad PCB compiler',
      body: 'For the bounded physical subset, map audited footprints, place them, route retained two-layer variants, and withhold failed boards.',
      stages: ['Source digest verification', 'Footprint mapping', 'Board placement', 'Two-layer routing', 'Pad-net validation', 'Clearance and outline checks'],
    },
    {
      index: '06',
      phase: 'Deliver',
      owner: 'Artifact boundary',
      body: 'Give the user a clean native project while retaining the evidence needed to reproduce, inspect, and improve the run.',
      stages: ['Native project download', 'Private internal bundle', 'Validation manifests', 'Serial and history record'],
    },
  ],
  marketSignals: [
    {
      value: '$20.78B',
      label: 'Estimated EDA tools market in 2026',
      source: 'Mordor Intelligence, June 2026',
      href: 'https://www.mordorintelligence.com/industry-reports/electronic-design-automation-eda-tools-market',
    },
    {
      value: '$30.67B',
      label: 'Projected EDA tools market in 2031',
      source: 'Mordor Intelligence, June 2026',
      href: 'https://www.mordorintelligence.com/industry-reports/electronic-design-automation-eda-tools-market',
    },
    {
      value: '8.1%',
      label: 'Reported 2026-2031 CAGR',
      source: 'Mordor Intelligence, June 2026',
      href: 'https://www.mordorintelligence.com/industry-reports/electronic-design-automation-eda-tools-market',
    },
    {
      value: '$40-85/hr',
      label: 'Electronics design engineer rate signal',
      source: 'Fiverr cost guide, March 2026',
      href: 'https://www.fiverr.com/resources/guides/costs/electronics-design-engineer',
    },
    {
      value: '$200-800',
      label: 'Simple PCB layout project signal',
      source: 'Upwork PCB designer guide, July 2026',
      href: 'https://www.upwork.com/hire/pcb-designers/',
    },
    {
      value: '$800-2.5K',
      label: 'Standard PCB design project signal',
      source: 'Upwork PCB designer guide, July 2026',
      href: 'https://www.upwork.com/hire/pcb-designers/',
    },
  ],
  businessLayers: [
    {
      stage: 'Wedge',
      title: 'Known circuits, expensive reconstruction',
      status: 'Current focus',
      body: 'Start where circuit intent is already understood but native project construction, validation, and cross-tool rebuilding still consume skilled time.',
      buyers: 'Students, teaching labs, freelancers, consultants',
    },
    {
      stage: 'Workflow',
      title: 'Reusable projects and controlled variants',
      status: 'Under work',
      body: 'History, serial reuse, deterministic edits, batch JSON generation, and shared artifacts turn one generation into an ongoing workspace.',
      buyers: 'Research labs and small engineering teams',
    },
    {
      stage: 'Infrastructure',
      title: 'Private, repeatable generation rails',
      status: 'Expansion',
      body: 'Private deployment, API access, team templates, usage controls, and validation evidence can make the compiler part of an internal engineering flow.',
      buyers: 'Hardware teams, consultancies, education programs',
    },
    {
      stage: 'Platform',
      title: 'More ecosystems without replacing the core',
      status: 'Long-term potential',
      body: 'Each source-backed exporter, validator, and component registry increases the number of workflows served by the same tool-neutral circuit contract.',
      buyers: 'EDA vendors, component ecosystems, enterprise integrations',
    },
  ],
  businessModel: [
    { label: 'Individuals', value: 'Usage and project limits', note: 'Potential paid generation and storage tiers' },
    { label: 'Teams', value: 'Workspace subscription', note: 'Private history, templates, batches, and controls*' },
    { label: 'Enterprise', value: 'Private deployment and API', note: 'Security, integrations, support, and governed access*' },
    { label: 'Ecosystem', value: 'Compiler and exporter partnerships', note: 'New native backends and component libraries*' },
  ],
  comparison: [
    { capability: 'What you receive', generic: 'Advice, prose, or code', closed: 'A diagram inside another editor', progen: 'A native project file' },
    { capability: 'Final syntax', generic: 'Probabilistic', closed: 'Platform-owned', progen: 'Deterministic exporter' },
    { capability: 'Tool choice', generic: 'Manual handoff', closed: 'One environment', progen: 'Existing EDA ecosystems' },
    { capability: 'Small revisions', generic: 'Ask the model again', closed: 'Edit in the platform', progen: 'Change JSON and recompile' },
    { capability: 'Validation evidence', generic: 'Best-effort answer', closed: 'Varies by platform', progen: 'Stage and backend checks' },
  ],
  competitiveLandscape: [
    {
      category: 'Existing EDA environments',
      examples: 'KiCad, Proteus, LTspice, Altium, Cadence, Siemens EDA',
      context: 'Powerful environments where engineers construct, inspect, simulate, and verify projects.',
      focus: 'ProGenEDA is an upstream compiler that produces files for the tools engineers already use.',
    },
    {
      category: 'AI-native and design automation',
      examples: 'Flux, Circuit Mind, CELUS, Quilter, Diode',
      context: 'A broad category spanning browser ECAD, architecture generation, component intelligence, and physical design.',
      focus: 'ProGenEDA focuses on one tool-neutral circuit contract compiled across multiple native backends.',
    },
    {
      category: 'Code-first and research systems',
      examples: 'JITX, pcbGPT and related DSL workflows',
      context: 'Evidence that programmatic and language-to-schematic workflows can produce editable engineering artifacts.',
      focus: 'ProGenEDA combines an accessible intent boundary with deterministic exporters and validators.',
    },
    {
      category: 'General-purpose AI',
      examples: 'ChatGPT, Claude, Gemini and code-generation models',
      context: 'Strong at explaining circuits and interpreting incomplete requests, but model output alone is not a file-validity guarantee.',
      focus: 'Models interpret intent; code owns final syntax, validation, packaging, history, and repeatable edits.',
    },
  ],
  evidence: [
    { value: '600/600', title: 'KiCad combination projects', body: 'Passed final validation and hosted local-netlist comparison in the accepted July corpus.' },
    { value: '300/300', title: 'Deterministic layout variations', body: 'One hundred imported circuits, three compiled variations each, without changing connectivity.' },
    { value: '495', title: 'Accepted PCB corpus boards*', body: 'All accepted boards passed the external KiCad 10.0.4 DRC oracle with zero violations.' },
  ],
  audiences: [
    { title: 'Students and labs', body: 'Start from editable files inside the native tools used in class and research.' },
    { title: 'Freelancers', body: 'Move from a clear client brief to a practical first project and controlled variants.' },
    { title: 'Engineering teams', body: 'Turn internal circuit patterns into repeatable, auditable generation workflows.' },
    { title: 'EDA ecosystems', body: 'Add a target exporter without retraining the intent layer for every file format.' },
  ],
  roadmap: [
    'Footprint assignment and compatibility reports',
    'Constrained board outlines and placement regions',
    'Rule-aware routing, copper zones, and DRC',
    'Gerber, drill, BOM, and manufacturing packages',
  ],
  assets: {
    hero: '/landing/hero-intent-to-file.webp',
    friction: '/landing/manual-friction.webp',
    schema: '/landing/intent-schema.webp',
    compiler: '/landing/deterministic-compiler.webp',
    ecosystems: '/landing/native-ecosystems.webp',
    simulation: '/landing/simulation-ready.webp',
    pcb: '/landing/pcb-roadmap.webp',
    productGenerate: '/screenshots/generate-july13-live.png',
    productHistory: '/screenshots/history-july13-live.png',
  },
} as const;
