from __future__ import annotations

import unittest
from unittest.mock import patch
from subprocess import CompletedProcess
import tempfile
from pathlib import Path

from ltspice.pipeline.component_placer import place_components
from ltspice.pipeline.component_selector import select_components
from ltspice.pipeline.ltspice_wire_maker import build_wire_plan
from ltspice.pipeline.native_pin_mapper import translate_circuit_pins
from ltspice.pipeline.oracle_netlist_validator import _expected_instance_name, parse_oracle_netlist, validate_oracle_netlist
from ltspice.pipeline.progen_ltspice_executable import parse_oracle_command
from ltspice.pipeline.simulation_validator import OracleCommand, run_external_oracle


def _rc_circuit() -> dict[str, object]:
    return {
        "components": [
            {"ref": "V1", "kind": "VSIN", "value": "SINE(0 1 1k)", "pins": {"1": "IN", "2": "GND"}},
            {"ref": "R1", "kind": "R", "value": "1k", "pins": {"1": "IN", "2": "OUT"}},
            {"ref": "C1", "kind": "C", "value": "1u", "pins": {"1": "OUT", "2": "GND"}},
            {"ref": "G1", "kind": "GND", "pins": {"1": "GND"}},
        ],
        "nets": {
            "IN": ["V1.1", "R1.1"],
            "OUT": ["R1.2", "C1.1"],
            "GND": ["V1.2", "C1.2", "G1.1"],
        },
        "routing": {"mode": "combination"},
    }


class OracleNetlistValidatorTests(unittest.TestCase):
    def test_cli_oracle_command_expands_environment_without_a_shell(self) -> None:
        with patch.dict("os.environ", {"PROGEN_TEST_HOME": "/tmp/progen-home"}, clear=False):
            command = parse_oracle_command(r"env WINEPREFIX=$PROGEN_TEST_HOME/prefix wine 'C:\Program Files\ADI\LTspice\LTspice.exe'")

        self.assertEqual(command[0:2], ["env", "WINEPREFIX=/tmp/progen-home/prefix"])
        self.assertEqual(command[-1], "C:\\Program Files\\ADI\\LTspice\\LTspice.exe")

    def _contract(self):
        circuit = _rc_circuit()
        selected, _selection_report = select_components(circuit)
        native, _translation = translate_circuit_pins(circuit, selected)
        placed, _placement_report = place_components(native, selected)
        return selected, build_wire_plan(native, placed)

    def test_prefix_wrappers_use_ltspice_section_sign_instance_names(self) -> None:
        selected, _report = select_components(
            {
                "components": [
                    {"ref": "Q1", "kind": "NPN", "pins": {"1": "BASE", "2": "COL", "3": "EMIT"}},
                    {"ref": "M1", "kind": "NMOS", "pins": {"1": "GATE", "2": "DRAIN", "3": "SOURCE"}},
                ]
            }
        )

        self.assertEqual(_expected_instance_name(selected[0]), "X§Q1")
        self.assertEqual(_expected_instance_name(selected[1]), "X§M1")

    def test_exported_netlist_compares_connectivity_without_auto_node_spelling(self) -> None:
        selected, wire_plan = self._contract()
        # N001 is LTspice's auto-generated direct-wire node rather than the
        # logical OUT label. The validator must prove the endpoint partition,
        # not require a synthetic label that was never written to the ASC.
        netlist = """* generated by LTspice\nV1 IN 0 SINE(0 1 1k)\nR1 IN N001 1k\nC1 N001 0 1u\n.tran 1u 5m\n.end\n"""

        report = validate_oracle_netlist(netlist, selected=selected, wire_plan=wire_plan)

        self.assertTrue(report["ok"], report)
        self.assertEqual(report["native_nets"]["OUT"]["node"], "N001")
        self.assertEqual(report["component_instances"]["R1"]["nodes_by_spice_order"], {"1": "IN", "2": "N001"})

    def test_exported_netlist_compares_spice_nodes_case_insensitively(self) -> None:
        selected, wire_plan = self._contract()
        netlist = """V1 in 0 SINE(0 1 1k)\nR1 IN n001 1k\nC1 N001 0 1u\n.end\n"""

        report = validate_oracle_netlist(netlist, selected=selected, wire_plan=wire_plan)

        self.assertTrue(report["ok"], report)

    def test_exported_netlist_rejects_a_split_expected_net(self) -> None:
        selected, wire_plan = self._contract()
        netlist = """V1 IN 0 SINE(0 1 1k)\nR1 IN N001 1k\nC1 IN 0 1u\n.end\n"""

        report = validate_oracle_netlist(netlist, selected=selected, wire_plan=wire_plan)

        self.assertFalse(report["ok"])
        self.assertTrue(any("split expected net 'OUT'" in error for error in report["errors"]))

    def test_oracle_failure_surfaces_the_native_netlist_reason(self) -> None:
        selected, wire_plan = self._contract()
        with tempfile.TemporaryDirectory() as temporary:
            asc_path = Path(temporary) / "fixture.asc"
            asc_path.write_text("Version 4\n", encoding="ascii")
            # R1.2 and C1.1 should be the same OUT node, but this forged
            # executable netlist splits them.  The top-level oracle result
            # must carry that specific reason for the UI/error report.
            asc_path.with_suffix(".net").write_text(
                "V1 IN 0 SINE(0 1 1k)\nR1 IN 0 1k\nC1 N001 0 1u\n.end\n",
                encoding="utf-8",
            )
            completed = CompletedProcess(["ltspice"], 0, "", "")
            with patch("ltspice.pipeline.simulation_validator.subprocess.run", return_value=completed):
                report = run_external_oracle(
                    asc_path,
                    oracle=OracleCommand(("ltspice",)),
                    selected=selected,
                    wire_plan=wire_plan,
                )

        self.assertFalse(report["ok"])
        self.assertTrue(any("split expected net 'OUT'" in error for error in report["errors"]))

    def test_continuation_lines_are_kept_as_one_instance(self) -> None:
        instances = parse_oracle_netlist("V1 IN 0 PULSE(0 5\n+ 0 1n 1n 1m 2m)\n.end\n")

        self.assertEqual(len(instances), 1)
        self.assertEqual(instances[0].name, "V1")
        self.assertIn("2m)", instances[0].text)
