from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT / "src"))

from proteusgen.component_placer import (  # noqa: E402
    MAIN_MEGA_NO_SOURCE_DONOR,
    NEW_COMPONENT_MEGA_DONOR,
    _repo_path,
    generate_component_placement_project,
)
from proteusgen.component_terminal_placer import (  # noqa: E402
    append_bidir_terminals_to_project,
    plan_side_bidir_terminals,
)


OUT_DIR = ROOT / "experiments" / "terminal_placer_bidir_probe_v1_temp_2026_06_26"
ARCHIVE = ROOT / "experiments" / "TERMINAL_PLACER_BIDIR_PROBE_V1_TEMP_2026_06_26.zip"


CASES = [
    {
        "case_id": "T01_PASSIVE_TWO_PIN_BIDIR_ATTACH",
        "payload": {
            "donor": str(_repo_path(MAIN_MEGA_NO_SOURCE_DONOR)),
            "components": {"RESISTOR": 3, "CAP": 3, "REALIND": 3, "DIODE": 3},
            "layout": {"strategy": "beautify"},
        },
    },
    {
        "case_id": "T02_SOURCE_AND_PASSIVE_BIDIR_ATTACH",
        "payload": {
            "donor": str(_repo_path(NEW_COMPONENT_MEGA_DONOR)),
            "components": {"VSOURCE": 3, "CSOURCE": 3, "RESISTOR": 3, "CAP-ELEC": 3},
            "layout": {"strategy": "beautify"},
        },
    },
]


def clean() -> None:
    if OUT_DIR.exists():
        shutil.rmtree(OUT_DIR)
    OUT_DIR.mkdir(parents=True)
    if ARCHIVE.exists():
        ARCHIVE.unlink()


def main() -> None:
    clean()
    summary = []
    for index, case in enumerate(CASES, start=1):
        case_id = case["case_id"]
        case_dir = OUT_DIR / f"{index:02d}_{case_id}"
        case_dir.mkdir()
        payload = case["payload"]
        base = case_dir / f"{case_id}_BASE.pdsprj"
        output = case_dir / f"{case_id}.pdsprj"
        result = generate_component_placement_project(payload, base, full_cdb=True)
        specs = plan_side_bidir_terminals(result.selected_groups, label_prefix=f"N{index}")
        terminal_report = append_bidir_terminals_to_project(base, output, specs)
        (case_dir / "payload.json").write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
        (case_dir / "base_manifest.json").write_text(json.dumps(result.as_dict(), indent=2) + "\n", encoding="utf-8")
        (case_dir / "terminal_plan.json").write_text(json.dumps(terminal_report, indent=2) + "\n", encoding="utf-8")
        summary.append(
            {
                "case_id": case_id,
                "base_valid": result.valid,
                "terminal_valid": terminal_report["valid"],
                "terminal_count_added": terminal_report["terminal_count_added"],
                "output": str(output.relative_to(OUT_DIR)),
            }
        )
    (OUT_DIR / "summary.json").write_text(json.dumps(summary, indent=2) + "\n", encoding="utf-8")
    (OUT_DIR / "README.md").write_text(
        "# Terminal Placer Bidir Probe V1\n\n"
        "These cases use the accepted component placer first, then append donor-derived `$TERBIDIR` records.\n"
        "No Proteus wire records are emitted. Inspect whether the bider terminals sit beside the component endpoint sides.\n"
        "The labels are generated by this stage so future wiring/naming work stays in one owner.\n",
        encoding="utf-8",
    )
    shutil.make_archive(str(ARCHIVE.with_suffix("")), "zip", OUT_DIR)
    print(json.dumps({"out_dir": str(OUT_DIR), "archive": str(ARCHIVE), "cases": len(summary)}, indent=2))


if __name__ == "__main__":
    main()
